### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [rioj7/fileGroup#3]
The [Open VSX Registry](https://open-vsx.org/?search=group) currently has no extension to . Open VSX Registry is the default extension provider endpoint for the free build of vscode VSCodium and Eclipse Theia. It would be nice to have this extension directly be published to a free vsix repository instead of only the Microsoft Marketplace with its restrictions.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by rioj7** [comment]
@GitMensch  I have been asked this also for another extension. I have looked into it and decide not to add the hassle of adding Open VSX to the release workflow.

**Comment by filiptronicek** [comment]
@rioj7 have you tried automating releases with GitHub Actions? I know publishing manually to both the Microsoft Marketplace and OpenVSX. If you want, I can help you set it up, but it should be as easy as following [a doc that I wrote about publishing directly](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md). It would help users to be able to install the extension on places where VS Code is used not by Microsoft, of which there are many.
