### ISSUE TITLE
FR: please add license to repository

### ISSUE THREAD

**Issue by GitMensch** [rioj7/fileGroup#5]
The license is clearly and correctly defined in the package.json - but it would be good to also have it in the repository, which adds it to the github metadata and also is shown in GH and several frontends.

Please see [GH Docs: Adding a license to a repository](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) - it should be done within 5 minutes (including the reading).

Thanks!

**Comment by rioj7** [comment]
@GitMensch  `vsce` also asks about a missing license file but still uploads the extension. If it is not open source do not put it in a public github project.

**Comment by GitMensch** [comment]
> it is not open source do not put it in a public github project.

That is not the point, but the point is to easily recognize what license it has. As noted above GH allows you to add the license with a drop-down, so everything is done very easy....
