### ISSUE TITLE
Error messages on opening file group

### ISSUE THREAD

**Issue by pm-ur** [rioj7/fileGroup#6]
I get error messages when I open a file group. The files do open fine, but I see error notifications like: "Could NOT open file ..." for each file.

**Comment by rioj7** [comment]
@pm-energid What could be different on your setup compared to the other extension users?

Are you trying to load remote files?

What is the full error message (without the file path part)? Part of the message is the extension creating the message.

Which version of VSC do you use and what OS?

VSCode has 2 methods of opening files.

I have written the extension [HTML Related Links](https://marketplace.visualstudio.com/items?itemName=rioj7.html-related-links#open-a-file) where you can open a file with a command in a key binding and select with method to use.

Can you try to open a file with both methods:

```
{
    "key": "ctrl+i r",
    "command": "htmlRelatedLinks.openFile",
    "args": {
      "file": "path-to-the-file",
      "method": "vscode.open"
    }
  }
```

Change `method` property to `openShow`

```
      "method": "openShow"
```

And see if there is a difference.

The extension has a setting `html-related-links.enableLogging`, if set it will show some extra info in the Console of VSC (**Help** > **Toggle Developer Tools** - Select **Console** tab)

You might clear the stuff there first with the second button on the toolbar (circle-with-slash)

**Comment by pm-ur** [comment]
At first, I thought it could be because my files were inside junctions (Windows directory links). But I did test it again using regular git repositories. My paths are specified as "D:/dir1/dir2/file.txt".

I'll try the other extension out and post results.

**Comment by pm-ur** [comment]
Found no issues with html-related-links. It opens a file without issues using both methods. Even with the File Group extension, I can open a single file without errors. However, the errors appear only when I have more than one file in the group. Sometimes it might not appear with just 2 files, and other times it'd appear even with just 2 files. So, I think the issue may relate to opening multiple files at once (within a short timespan).

BTW.. it is worth noting that all the files in the group are opened correctly. Just that the error message is displayed after opening each file.

**Comment by pm-ur** [comment]
For now, I've removed the error handling (`vscode.window.showErrorMessage(String(error));`) from the extension.js file and its behavior "seems" normal. Although the promise is being rejected behind the scenes for some reason, the files do open as expected. It's not ideal, but let's me work without noisy notifications for now until the bug can be fixed.

**Comment by rioj7** [comment]
@pm-energid 

This is the text I get for opening a non-existing file. Is your error message identical (apart from the file path)?

```
Error: cannot open file:///d%3A/test/mysite1/testX.html.
Detail: Unable to read file 'd:\test\mysite1\testX.html'
(Error: Unable to resolve nonexistent file 'd:\test\mysite1\testX.html')

Source: File Group (Extension)
```

I have changed the loading to be sequential in v1.0.2, can you try this.

**Comment by pm-ur** [comment]
Lol. I was trying to reproduce the correct error messages and couldn't since the files were loading slower now. Took me a little while to figure out that the extension was updated automatically behind the scenes to v1.0.2. The sequential update seems to resolve it for me.

However, I reinstalled v1.0.1 to get the error message. It's like this:
```
Error: Could NOT open editor for "file:///d%3A/d/ws/mydir/setup.cmake".

Source: File Group (Extension)
```

**Comment by pm-ur** [comment]
Thanks for patching it immediately though :)

**Comment by rioj7** [comment]
@pm-energid The fact that removing `vscode.window.showErrorMessage` prevents the error message, is strange, the open file call returns a Thenable (Promise like) and in the `.then()` call you pass 2 function, 1 to call if success and 1 to call on error. So the file loads but the error function is called.

Maybe a different version of VSC has a different Error Message.

How much slower is the loading?

I can add settings to

* choose Sequential-Parallel
* choose ShowError Message Yes/No
* choose to use `vscode.open` or `showTextDocument`

I prefer to show the error if the file is not found.

**Comment by pm-ur** [comment]
It's slower than before, but not much. It's "almost" as fast (~80-90%). I think what you have now is quite good without any additional options.

**Comment by rioj7** [comment]
@pm-energid  Then I will not get a lot of remarks from users ;-)

I now think the disk file loading is not overlapping VSC document/editor stuff anymore, the VSC was already sequential because Node (JavaScript) is single threaded. I now start a new file the moment the previous is visible (the Promise resolves)

Now I wait till somebody has a request to load remote files in a group, or load local files on the remote VSC.

Maybe I will one day use the `vscode.open` method, I once read (can't find the page anymore) that that now has the preference to use, but in the doc they say if you need more options use `showTextDocument`.

I close the issue for now.
