### ISSUE TITLE
Support for remote workspaces

### ISSUE THREAD

**Issue by pm-ur** [rioj7/fileGroup#7]
This extension doesn't work in workspaces/folders over SSH/WSL. The first error we can't get through is its dependency on the "multiCommand" extension, which can't be loaded in remote workspaces. It would be great if you could provide support for remote SSH workspaces.

**Comment by rioj7** [comment]
@pm-energid  Why can't you use multi-command in remote workspaces

multi-command is only needed if you use scripts.

**Comment by pm-ur** [comment]
Multicommand extension fails to load on remote sessions

**Comment by rioj7** [comment]
@pm-energid The reason multi-command is not run on the remote host is because the extension `package.json` states that it prefers to run on the UI side. I see no reason why I would run multi-command in the UI.

You can override that behavior by setting `remote.extensionKind`.

Add this to your Global `settings.json`

```
  "remote.extensionKind": {
    "ryuta46.multi-command": ["workspace"]
  }
```

Now you can install File Group on the remote and it should be enabled.

I tested it on a SSH remote Linux.

VSC doc: [Advanced: Forcing an extension to run locally / remotely](https://code.visualstudio.com/docs/remote/ssh#_advanced-forcing-an-extension-to-run-locally-remotely)

**Comment by pm-ur** [comment]
That change didn't help. This is what I get:
![image](https://user-images.githubusercontent.com/14093541/180495029-d31505ef-df36-44bd-8f22-3a38023f657d.png)

I get the same error message after reloading the window.

**Comment by rioj7** [comment]
@pm-energid 

I had that same error.

You have to change the `settings.json` of the local VSC (when remote is not connected)

**Comment by pm-ur** [comment]
I did that.. but I made a silly mistake. I wrote `ryuta.multi...` instead of `ryuta46.multi...`. Took me a while to figure it out 😆. Thanks! It's working now.

**Comment by White-Owl** [comment]
@rioj7 
Add this into documentation, please.
Had same problem and almost submitted new issue before decided to check closed ones.

**Comment by rioj7** [comment]
@White-Owl Good point. See v1.0.3

**Comment by pm-energid** [comment]
This is what I get:
***@***.***


Please note that this message may contain confidential information. If you have received this message by mistake, please inform the sender of the mistake, then delete the message from your system without making, distributing or retaining any copies of it. Although we believe that the message and any attachments are free from viruses and other errors that might affect the computer or IT system where it is received and read, the recipient opens the message at his or her own risk. We assume no responsibility for any loss or damage arising from the receipt or use of this message.

When we process personal data relating to physical persons, such processing will meet the requirements of applicable data protection legislation and will be in accordance with our Privacy Policy https://www.energid.com/privacy

**Comment by rioj7** [comment]
@pm-energid I have edited you last comment. I don't understand it.

**Comment by pm-energid** [comment]
I didn't add any comment 2 days ago. I'll investigate why it says I did.

**Comment by pm-energid** [comment]
@rioj7 I can't see what was the message before you edited it. I don't see any recent logins on my account security log for over a month before today. Either someone spoofed my user name or it was a glitch in GitHub.

**Comment by rioj7** [comment]
@pm-energid  If you click on the triangle in the comment of 2022-10-11 you can see the original message, it looks like a reply to an email send by Github, if it is an error you can delete the comments you made after that date

**Comment by pm-energid** [comment]
ok @rioj7. It looks like the email application on windows might have an old draft that was sent when I opened the same app after months :). I'll delete the comments now.. thanks!
